services:
  - type: web
    name: beverage-predictor
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn web_server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: "10000"
